### ISSUE TITLE
Add TriMet

### ISSUE THREAD

**Issue by davidcelis** [kona314/transit-fedilerts#4]
Hey, thanks for this project! It may already be on your list somewhere, but it’d be great to get a TriMet account following their GTFS data. TriMet serves the greater Portland Metro area. Documentation is available here: https://developer.trimet.org/GTFS.shtml

**Comment by kona314** [comment]
Yup, on the list! Slated for an upcoming batch of new agencies.

**Comment by kona314** [comment]
Available at @trimet@transit.alerts.social
