### ISSUE TITLE
Add TransLink (Metro Vancouver, BC)

### ISSUE THREAD

**Issue by dpogue** [kona314/transit-fedilerts#5]
**Agency name:** TransLink
**City/region/other locality:** Metro Vancouver, BC, Canada

**Link to alerts feed docs/info (if known):** 
* GTFS Real-time documentation: https://www.translink.ca/about-us/doing-business-with-translink/app-developer-resources/gtfs/gtfs-realtime

* Requires registering for an API key: https://www.translink.ca/about-us/doing-business-with-translink/app-developer-resources/register

* Other developer resources: https://www.translink.ca/about-us/doing-business-with-translink/app-developer-resources

**Comment by kona314** [comment]
Now available at @translink@transit.alerts.social
