### ISSUE TITLE
Add NYC MTA

### ISSUE THREAD

**Issue by mattkatz** [kona314/transit-fedilerts#6]
I believe service alerts are published for each line.

**Comment by kona314** [comment]
Added:

@nyc_bus@transit.alerts.social
@nyc_subway@transit.alerts.social
@nyc_lirr@transit.alerts.social
@nyc_mnr@transit.alerts.social

These follow [the divisions the MTA makes](https://api.mta.info/#/serviceAlerts) with the source feeds.
